// LOGOUT 
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_RECEIVE = "LOGOUT_RECEIVE";

// LOGIN TOKEN
export const GET_TOKEN_REQUEST = "GET_TOKEN_REQUEST";
export const GET_TOKEN_RECEIVE = "GET_TOKEN_RECEIVE";

// RESEND VERIFICATION CODE
export const RESEND_VERIFICATION_CODE_REQUEST = "RESEND_VERIFICATION_CODE_REQUEST";
export const RESEND_VERIFICATION_CODE_RECIEVE = "RESEND_VERIFICATION_CODE_RECIEVE";