export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_RECEIVE = "LOGOUT_RECEIVE";
export const GET_TOKEN_REQUEST = "GET_TOKEN_REQUEST";
export const GET_TOKEN_RECEIVE = "GET_TOKEN_RECEIVE";
//GET FIREBASE TOKEN
export const GET_FIREBASE_TOKEN_REQUEST = "GET_FIREBASE_TOKEN_REQUEST";