// LOGOUT
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_RECEIVE = "LOGOUT_RECEIVE";

// LOGIN OTP
export const GET_TOKEN_REQUEST = "GET_TOKEN_REQUEST";
export const GET_TOKEN_RECEIVE = "GET_TOKEN_RECEIVE";

// RESEND VERIFICATION CODE
export const RESEND_VERIFICATION_CODE_REQUEST =
  "RESEND_VERIFICATION_CODE_REQUEST";
export const RESEND_VERIFICATION_CODE_RECIEVE =
  "RESEND_VERIFICATION_CODE_RECIEVE";

// LOGIN TOKEN
export const GET_LOGIN_TOKEN_REQUEST = "GET_LOGIN_TOKEN_REQUEST";
export const GET_LOGIN_TOKEN_RECEIVE = "GET_LOGIN_TOKEN_RECEIVE";

// FORGET PASSWORD
export const FORGET_PASSWORD_REQUEST = "FORGET_PASSWORD_REQUEST";
export const FORGET_PASSWORD_RECEIVE = "FORGET_PASSWORD_RECEIVE";

// RESET PASSWORD
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_RECEIVE = "RESET_PASSWORD_RECEIVE";
