export const SET_LANG = "SET_LANG";
export const GET_LANG = "GET_LANG";
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
export const SHOW_SNACKBAR = "SHOW_SNACKBAR";
export const HIDE_SNACKBAR = "HIDE_SNACKBAR";
// fetch contributors
export const GET_CONTRIBUTORS_REQUEST = "GET_CONTRIBUTORS_REQUEST";
export const GET_CONTRIBUTORS_RECEIVE = "GET_CONTRIBUTORS_RECEIVE";
// search contributors
export const SEARCH_CONTRIBUTORS_REQUEST = "SEARCH_CONTRIBUTORS_REQUEST";
export const SEARCH_CONTRIBUTORS_RECEIVE = "SEARCH_CONTRIBUTORS_RECEIVE";
// fetch bsa
export const GET_BSA_REQUEST = "GET_BSA_REQUEST";
export const GET_BSA_RECEIVE = "GET_BSA_RECEIVE";
// sme
export const SME_UPCOMING_SESSIONS_REQUEST = "SME_UPCOMING_SESSIONS_REQUEST";
export const SME_UPCOMING_SESSIONS_RECEIVE = "SME_UPCOMING_SESSIONS_RECEIVE";
export const SME_SESSIONS_HISTORY_REQUEST = "SME_SESSIONS_HISTORY_REQUEST";
export const SME_SESSIONS_HISTORY_RECEIVE = "SME_SESSIONS_HISTORY_RECEIVE";
export const SME_SESSION_DETAILS_REQUEST = "SME_SESSION_DETAILS_REQUEST";
export const SME_SESSION_DETAILS_RECEIVE = "SME_SESSION_DETAILS_RECEIVE";
// disabled
export const SHOW_DISABLED = "SHOW_DISABLED";
export const HIDE_DISABLED = "HIDE_DISABLED";
// sme requsts
export const SME_REQUESTS_REQUEST = "SME_REQUESTS_REQUEST";
export const SME_REQUESTS_RECEIVE = "SME_REQUESTS_RECEIVE";

// SME COMPANIES
export const SME_COMPANIES_REQUEST = "SME_COMPANIES_REQUEST";
export const SME_COMPANIES_RECEIVE = "SME_COMPANIES_RECEIVE";

// SME RATE
// QUESTIONNAERS
export const QUESTIONNAIR_REQUEST = "QUESTIONNAIR_REQUEST";
export const QUESTIONNAIR_RECEIVE = "QUESTIONNAIR_RECEIVE";

// VALIDATE TOKEN 
export const VALIDATE_TOKEN_REQUEST = "VALIDATE_TOKEN_REQUEST";
export const VALIDATE_TOKEN_RECEIVE = "VALIDATE_TOKEN_RECEIVE";

//SUBMIT RATE
export const SUBMIT_RATE_REQUEST = "SUBMIT_RATE_REQUEST";
export const SUBMIT_RATE_RECEIVE = "SUBMIT_RATE_RECEIVE";


//SME  ALREADY RATED
export const IS_ALREADY_RATED = "IS_ALREADY_RATED"
